### ISSUE TITLE
One-way configuration is broken

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.MessagingBridge#294]
#### Description

Creating a bridge setup as shown in the one-way unit test results in the following startup error:

```txt
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at EndpointRegistry.ApplyMappings(IReadOnlyCollection`1 transportConfigurations) in S:\NServiceBus.MessagingBridge\src\NServiceBus.MessagingBridge\EndpointRegistry.cs:line 47
   at StartableBridge.Start(CancellationToken cancellationToken) in S:\NServiceBus.MessagingBridge\src\NServiceBus.MessagingBridge\StartableBridge.cs:line 73
   at BridgeHostedService.StartAsync(CancellationToken cancellationToken) in S:\NServiceBus.MessagingBridge\src\NServiceBus.MessagingBridge\Hosting\BridgeHostedService.cs:line 24
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.Main() in R:\SimpleOneWayBridge\Bridge\Program.cs:line 14
   at Program.<Main>()
```

The reason for it is that the bridge assumes that each transport has at least a single receive proxy and will use the first proxy it can find to (ab)use this for sending on that transport too.

However, that isn't sufficient. Assuming a send proxy can be resolved transferring a message would still fail as the source isn't known by the mapper when analyzing the `NServiceBus.ReplyToAddress` header with the following error:

```txt
09:24:13 fail: MessageShovelErrorHandlingPolicy[0] Message shovel operation failed, message will be moved to bridge.error System.Exception: Failed to shovel message for endpoint Samples.Bridge.RightReceiver with id 350b8678-57b2-4b46-9b79-d2d0601f6940 from left to right
  ---> System.Exception: No target address mapping could be found for source address: Samples.Bridge.LeftSender. Ensure names have correct casing as mappings are case-sensitive. Nearest configured match: Samples.Bridge.RightReceiver
    at EndpointRegistry.TranslateToTargetAddress(String sourceAddress) in S:\NServiceBus.MessagingBridge\src\NServiceBus.MessagingBridge\EndpointRegistry.cs:line 92
    at MessageShovel.TransformAddressHeader(OutgoingMessage messageToSend, IEndpointRegistry targetEndpointRegistry, String headerKey) in S:\NServiceBus.MessagingBridge\src\NServiceBus.MessagingBridge\MessageShovel.cs:line 95
    at MessageShovel.TransferMessage(TransferContext transferContext, CancellationToken cancellationToken) in S:\NServiceBus.MessagingBridge\src\NServiceBus.MessagingBridge\MessageShovel.cs:line 58
    --- End of inner exception stack trace ---
    at MessageShovel.TransferMessage(TransferContext transferContext, CancellationToken cancellationToken) in S:\NServiceBus.MessagingBridge\src\NServiceBus.MessagingBridge\MessageShovel.cs:line 74
    at NServiceBus.LearningTransportMessagePump.ProcessFile(ILearningTransportTransaction transaction, String messageId, CancellationToken messageProcessingCancellationToken) in /_/src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs:line 340
```

#### Versions

Version https://github.com/Particular/NServiceBus.MessagingBridge/releases/tag/2.0.2 introduced a less strict configuration.

### Steps to reproduce

1. Setup a bridge with a similar config like the following:
```c#
.UseNServiceBusBridge((ctx, bridgeConfiguration) =>
{
    var left = new BridgeTransport(new LearningTransport
        { StorageDirectory = Path.Combine(Path.GetTempPath(), "Left") })
    {
        Name = "left"
    };
    var right = new BridgeTransport(new LearningTransport
        { StorageDirectory = Path.Combine(Path.GetTempPath(), "Right") })
    {
        Name = "right"
    };

    right.HasEndpoint("RightReceiver");

    bridgeConfiguration.AddTransport(left);
    bridgeConfiguration.AddTransport(right);
});
```
2. Observe that the bridge fails at start.

## Workaround

Don't use one-way configuration by not having `HasEndpoint`.

**Comment by ramonsmits** [comment]
## Solution suggestion

### Proxies

The bridge could create a send proxy for each transport instead of resolving any of the receive proxies for a transport.

### ReplyTo header value

The problem with the ReplyTo header can be mitigated by either of the following solutions

1. By allowing ReplyTo header values for which no mapping exists, potentially only after explicitly disabling this validation.
2. Still use `HasEndpoint` but with an argument to define its "one-way" and doing this will not create a receiver proxies on any transport but will ensure mappings are explicitly created.
```c#
left.HasEndpoint(new BridgeEndpoint("LeftSender") { OneWay = true });
// or
left.HasEndpoint(new BridgeEndpoint("LeftSender") { SendOnly = true });
```

**Comment by ramonsmits** [comment]
We are reverting the change from 2.0.2 and release 2.0.3 soon to restore the behavior as it was before 2.0.2

**Comment by ramonsmits** [comment]
We've released https://github.com/Particular/NServiceBus.MessagingBridge/releases/tag/2.0.3 that reverts this.
